-- ClassKitConstants.lua
-- Server- und Client-gemeinsame Waffenprofile der neun Klassen.

local Constants = {}

export type DiscProfile = {
	name: string,
	projectileSpeed: number,
	projectileRadius: number,
	projectileColor: Color3,
	splashMaxDamage: number,
	splashMinDamage: number,
	splashRadius: number,
	directDamage: number,
	fireCooldown: number,
	selfKnockbackScale: number,
	gravity: number?,
	homingStrength: number?,
	homingRange: number?,
	burstCount: number?,
	burstInterval: number?,
}

export type AutomaticProfile = {
	name: string,
	maxRange: number,
	damagePerHit: number,
	minFireInterval: number,
	maxFireInterval: number,
	spinUpTime: number,
	spreadAngle: number,
	heatPerShot: number,
	heatCooldownRate: number,
	overheatLockout: number,
	tracerColor: Color3,
	pellets: number?,
	zoomFov: number?,
	tracerWidth: number?,
	singleShotCooldown: number?,
}

export type GrenadeProfile = {
	name: string,
	fuseTime: number,
	explodeOnImpact: boolean,
	stickOnImpact: boolean,
	causesFlagFumble: boolean,
	throwSpeed: number,
	radius: number,
	maxDamage: number,
	minDamage: number,
	knockbackSpeed: number,
	knockbackUpSpeed: number,
	color: Color3,
}

export type ClassKit = {
	disc: DiscProfile,
	automatic: AutomaticProfile,
	grenade: GrenadeProfile,
}

Constants.KITS = {
	Pathfinder = {
		disc = {
			name = "Light Spinfusor",
			projectileSpeed = 205,
			projectileRadius = 0.45,
			projectileColor = Color3.fromRGB(75, 205, 255),
			splashMaxDamage = 64,
			splashMinDamage = 28,
			splashRadius = 17,
			directDamage = 88,
			fireCooldown = 1.3,
			selfKnockbackScale = 1.08,
		},
		automatic = {
			name = "Light Assault Rifle",
			maxRange = 280,
			damagePerHit = 7,
			minFireInterval = 0.085,
			maxFireInterval = 0.28,
			spinUpTime = 0.55,
			spreadAngle = 2,
			heatPerShot = 4.5,
			heatCooldownRate = 40,
			overheatLockout = 1.5,
			tracerColor = Color3.fromRGB(255, 225, 130),
			singleShotCooldown = 0.42,
		},
		grenade = {
			name = "Impact Nitron",
			fuseTime = 3,
			explodeOnImpact = true,
			stickOnImpact = false,
			causesFlagFumble = true,
			throwSpeed = 72,
			radius = 17,
			maxDamage = 65,
			minDamage = 20,
			knockbackSpeed = 68,
			knockbackUpSpeed = 30,
			color = Color3.fromRGB(80, 210, 255),
		},
	},
	Sentinel = {
		disc = {
			name = "Nova Blaster",
			projectileSpeed = 225,
			projectileRadius = 0.35,
			projectileColor = Color3.fromRGB(120, 235, 255),
			splashMaxDamage = 50,
			splashMinDamage = 20,
			splashRadius = 13,
			directDamage = 72,
			fireCooldown = 0.9,
			selfKnockbackScale = 0.72,
		},
		automatic = {
			name = "BXT1 Rifle",
			maxRange = 450,
			damagePerHit = 48,
			minFireInterval = 1.05,
			maxFireInterval = 1.05,
			spinUpTime = 0.01,
			spreadAngle = 0.2,
			heatPerShot = 25,
			heatCooldownRate = 45,
			overheatLockout = 1.2,
			tracerColor = Color3.fromRGB(120, 235, 255),
			zoomFov = 32,
			tracerWidth = 0.08,
			singleShotCooldown = 1.05,
		},
		grenade = {
			name = "Grenade XL",
			fuseTime = 2.4,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 66,
			radius = 22,
			maxDamage = 75,
			minDamage = 22,
			knockbackSpeed = 52,
			knockbackUpSpeed = 24,
			color = Color3.fromRGB(115, 225, 255),
		},
	},
	Infiltrator = {
		disc = {
			name = "Stealth Light Spinfusor",
			projectileSpeed = 210,
			projectileRadius = 0.4,
			projectileColor = Color3.fromRGB(165, 95, 255),
			splashMaxDamage = 60,
			splashMinDamage = 25,
			splashRadius = 15,
			directDamage = 84,
			fireCooldown = 1.25,
			selfKnockbackScale = 0.95,
		},
		automatic = {
			name = "Rhino SMG",
			maxRange = 250,
			damagePerHit = 6,
			minFireInterval = 0.065,
			maxFireInterval = 0.16,
			spinUpTime = 0.25,
			spreadAngle = 2.8,
			heatPerShot = 4,
			heatCooldownRate = 45,
			overheatLockout = 1.4,
			tracerColor = Color3.fromRGB(185, 105, 255),
			singleShotCooldown = 0.28,
		},
		grenade = {
			name = "Sticky Grenade",
			fuseTime = 1.8,
			explodeOnImpact = false,
			stickOnImpact = true,
			causesFlagFumble = false,
			throwSpeed = 68,
			radius = 14,
			maxDamage = 78,
			minDamage = 28,
			knockbackSpeed = 48,
			knockbackUpSpeed = 20,
			color = Color3.fromRGB(175, 85, 255),
		},
	},
	Soldier = {
		disc = {
			name = "Spinfusor",
			projectileSpeed = 196,
			projectileRadius = 0.5,
			projectileColor = Color3.fromRGB(65, 170, 255),
			splashMaxDamage = 70,
			splashMinDamage = 35,
			splashRadius = 18,
			directDamage = 98,
			fireCooldown = 1.5,
			selfKnockbackScale = 1,
		},
		automatic = {
			name = "Assault Rifle",
			maxRange = 300,
			damagePerHit = 9,
			minFireInterval = 0.09,
			maxFireInterval = 0.32,
			spinUpTime = 0.7,
			spreadAngle = 2.2,
			heatPerShot = 5.5,
			heatCooldownRate = 35,
			overheatLockout = 1.8,
			tracerColor = Color3.fromRGB(255, 205, 95),
			singleShotCooldown = 0.38,
		},
		grenade = {
			name = "AP Grenade",
			fuseTime = 2.2,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 65,
			radius = 18,
			maxDamage = 85,
			minDamage = 25,
			knockbackSpeed = 55,
			knockbackUpSpeed = 24,
			color = Color3.fromRGB(255, 155, 45),
		},
	},
	Technician = {
		disc = {
			name = "Thumper",
			projectileSpeed = 160,
			projectileRadius = 0.5,
			projectileColor = Color3.fromRGB(90, 255, 155),
			splashMaxDamage = 75,
			splashMinDamage = 32,
			splashRadius = 18,
			directDamage = 90,
			fireCooldown = 1.35,
			selfKnockbackScale = 0.82,
			gravity = 28,
		},
		automatic = {
			name = "TCN4 SMG",
			maxRange = 260,
			damagePerHit = 7,
			minFireInterval = 0.075,
			maxFireInterval = 0.22,
			spinUpTime = 0.35,
			spreadAngle = 2.5,
			heatPerShot = 4.5,
			heatCooldownRate = 42,
			overheatLockout = 1.5,
			tracerColor = Color3.fromRGB(110, 255, 165),
			singleShotCooldown = 0.33,
		},
		grenade = {
			name = "TCN Grenade",
			fuseTime = 2.1,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 64,
			radius = 17,
			maxDamage = 80,
			minDamage = 25,
			knockbackSpeed = 52,
			knockbackUpSpeed = 22,
			color = Color3.fromRGB(90, 240, 145),
		},
	},
	Raider = {
		disc = {
			name = "ARX Buster",
			projectileSpeed = 175,
			projectileRadius = 0.52,
			projectileColor = Color3.fromRGB(255, 205, 70),
			splashMaxDamage = 42,
			splashMinDamage = 18,
			splashRadius = 14,
			directDamage = 56,
			fireCooldown = 1.45,
			selfKnockbackScale = 0.88,
			burstCount = 3,
			burstInterval = 0.14,
		},
		automatic = {
			name = "NJ5 SMG",
			maxRange = 280,
			damagePerHit = 8,
			minFireInterval = 0.075,
			maxFireInterval = 0.2,
			spinUpTime = 0.3,
			spreadAngle = 2.3,
			heatPerShot = 5,
			heatCooldownRate = 38,
			overheatLockout = 1.7,
			tracerColor = Color3.fromRGB(255, 215, 85),
			singleShotCooldown = 0.31,
		},
		grenade = {
			name = "EMP Grenade",
			fuseTime = 2,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 67,
			radius = 21,
			maxDamage = 62,
			minDamage = 20,
			knockbackSpeed = 44,
			knockbackUpSpeed = 18,
			color = Color3.fromRGB(80, 180, 255),
		},
	},
	Juggernaut = {
		disc = {
			name = "Heavy Spinfusor",
			projectileSpeed = 180,
			projectileRadius = 0.6,
			projectileColor = Color3.fromRGB(255, 155, 65),
			splashMaxDamage = 82,
			splashMinDamage = 42,
			splashRadius = 20,
			directDamage = 110,
			fireCooldown = 1.7,
			selfKnockbackScale = 0.82,
		},
		automatic = {
			name = "X1 LMG",
			maxRange = 310,
			damagePerHit = 11,
			minFireInterval = 0.105,
			maxFireInterval = 0.38,
			spinUpTime = 0.95,
			spreadAngle = 2.7,
			heatPerShot = 6.5,
			heatCooldownRate = 28,
			overheatLockout = 2.2,
			tracerColor = Color3.fromRGB(255, 145, 70),
			singleShotCooldown = 0.48,
		},
		grenade = {
			name = "Heavy AP Grenade",
			fuseTime = 2.5,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 58,
			radius = 20,
			maxDamage = 100,
			minDamage = 35,
			knockbackSpeed = 60,
			knockbackUpSpeed = 26,
			color = Color3.fromRGB(255, 105, 45),
		},
	},
	Brute = {
		disc = {
			name = "Heavy Spinfusor",
			projectileSpeed = 178,
			projectileRadius = 0.62,
			projectileColor = Color3.fromRGB(255, 95, 90),
			splashMaxDamage = 86,
			splashMinDamage = 44,
			splashRadius = 21,
			directDamage = 114,
			fireCooldown = 1.65,
			selfKnockbackScale = 0.8,
		},
		automatic = {
			name = "Auto Shotgun",
			maxRange = 120,
			damagePerHit = 5,
			minFireInterval = 0.55,
			maxFireInterval = 0.55,
			spinUpTime = 0.01,
			spreadAngle = 7,
			heatPerShot = 12,
			heatCooldownRate = 32,
			overheatLockout = 1.8,
			tracerColor = Color3.fromRGB(255, 115, 95),
			pellets = 8,
			tracerWidth = 0.09,
			singleShotCooldown = 0.7,
		},
		grenade = {
			name = "Fractal Grenade",
			fuseTime = 2.3,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 58,
			radius = 22,
			maxDamage = 105,
			minDamage = 36,
			knockbackSpeed = 62,
			knockbackUpSpeed = 28,
			color = Color3.fromRGB(255, 85, 80),
		},
	},
	Doombringer = {
		disc = {
			name = "Saber Launcher",
			projectileSpeed = 240,
			projectileRadius = 0.48,
			projectileColor = Color3.fromRGB(255, 230, 80),
			splashMaxDamage = 62,
			splashMinDamage = 28,
			splashRadius = 15,
			directDamage = 115,
			fireCooldown = 1.8,
			selfKnockbackScale = 0.55,
			homingStrength = 4.5,
			homingRange = 170,
		},
		automatic = {
			name = "Chaingun",
			maxRange = 330,
			damagePerHit = 12,
			minFireInterval = 0.1,
			maxFireInterval = 0.42,
			spinUpTime = 1.1,
			spreadAngle = 2.4,
			heatPerShot = 6.8,
			heatCooldownRate = 26,
			overheatLockout = 2.3,
			tracerColor = Color3.fromRGB(255, 235, 90),
			singleShotCooldown = 0.5,
		},
		grenade = {
			name = "Frag Grenade",
			fuseTime = 2.6,
			explodeOnImpact = false,
			stickOnImpact = false,
			causesFlagFumble = false,
			throwSpeed = 55,
			radius = 21,
			maxDamage = 95,
			minDamage = 32,
			knockbackSpeed = 58,
			knockbackUpSpeed = 25,
			color = Color3.fromRGB(255, 220, 70),
		},
	},
} :: { [string]: ClassKit }

function Constants.Get(loadoutId: any): ClassKit
	if typeof(loadoutId) == "string" and Constants.KITS[loadoutId] then
		return Constants.KITS[loadoutId]
	end
	return Constants.KITS.Pathfinder
end

return Constants
