"""Generate two original biomechanical factions for all nine CTFGame classes."""

import bpy
import glob
import json
import math
import os
import sys
from mathutils import Vector


ROOT = os.path.dirname(os.path.abspath(__file__))
EXPORT_DIR = os.path.join(ROOT, "export")
PREVIEW_DIR = os.path.join(ROOT, "previews")
BLEND_PATH = os.path.join(ROOT, "CTFGame_ClassArmor_v01.blend")
REPORT_PATH = os.path.join(ROOT, "class_armor_report.json")
SKIP_RENDER = "--skip-render" in sys.argv
RENDER_FILTER = next((arg.split("=", 1)[1] for arg in sys.argv if arg.startswith("--render-filter=")), None)
os.makedirs(EXPORT_DIR, exist_ok=True)
os.makedirs(PREVIEW_DIR, exist_ok=True)

# Outputs are entirely generated by this script. Remove armor files from the
# previous art direction so a rebuilt package can never mix both factions.
generated_patterns = []
if RENDER_FILTER is None:
    generated_patterns.extend((
        os.path.join(EXPORT_DIR, "*_Armor.fbx"),
        os.path.join(PREVIEW_DIR, "*_Armor.png"),
    ))
for generated_pattern in generated_patterns:
    for generated_path in glob.glob(generated_pattern):
        os.remove(generated_path)

CLASSES = [
    ("Pathfinder", "Light", "Aero fins and compact jetpack"),
    ("Sentinel", "Light", "Sensor crown and rangefinder"),
    ("Infiltrator", "Light", "Low profile phase nodes"),
    ("Soldier", "Medium", "Balanced segmented battle shell"),
    ("Technician", "Medium", "Repair symbiote and utility pods"),
    ("Raider", "Medium", "EMP coils and strike plates"),
    ("Juggernaut", "Heavy", "Siege pauldrons and dorsal reactor"),
    ("Brute", "Heavy", "Ram carapace and shock nodes"),
    ("Doombringer", "Heavy", "Fortress plating and shield emitters"),
]

FACTIONS = [
    ("CryoRevenant", "Blue", (0.12, 0.78, 1.0), "Biomechanical skeleton powered by frozen soul-energy"),
    ("EmberBrood", "Red", (1.0, 0.18, 0.035), "Living alien carapace fed by a molten crystal core"),
]


def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for collection in list(bpy.data.collections):
        if collection.name != "Collection":
            bpy.data.collections.remove(collection)


def material(name, color, metallic, roughness, emission=0.0):
    mat = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*color, 1)
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    emission_color = bsdf.inputs.get("Emission Color") or bsdf.inputs.get("Emission")
    if emission_color:
        emission_color.default_value = (*color, 1)
    emission_strength = bsdf.inputs.get("Emission Strength")
    if emission_strength:
        emission_strength.default_value = emission
    return mat


def move(obj, collection):
    for current in list(obj.users_collection):
        current.objects.unlink(obj)
    collection.objects.link(obj)


def finish(obj, mat, bevel=0.055):
    obj.data.materials.append(mat)
    modifier = obj.modifiers.new("ArmorBevel", "BEVEL")
    modifier.width = bevel
    modifier.segments = 2
    modifier.limit_method = "ANGLE"
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    return obj


def box(collection, name, size, location, mat, rotation=(0, 0, 0), bevel=0.055):
    bpy.ops.mesh.primitive_cube_add(location=location, rotation=rotation)
    obj = bpy.context.object
    obj.name = name
    obj.scale = tuple(value / 2 for value in size)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    move(obj, collection)
    return finish(obj, mat, bevel)


def cylinder(collection, name, radius, depth, location, mat, rotation=(0, 0, 0), vertices=16):
    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=depth, location=location, rotation=rotation)
    obj = bpy.context.object
    obj.name = name
    move(obj, collection)
    return finish(obj, mat, 0.035)


def sphere(collection, name, scale, location, mat):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=16, ring_count=8, radius=1, location=location)
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    move(obj, collection)
    return finish(obj, mat, 0.025)


def build_cryo_revenant(collection, weight, accent):
    heavy = weight == "Heavy"
    medium = weight == "Medium"
    plate = 1.28 if heavy else (1.08 if medium else 0.88)
    bone = bpy.data.materials["MAT_CryoBone"]
    dark = bpy.data.materials["MAT_CryoIron"]

    # A mechanical skull replaces the familiar Roblox head silhouette.
    sphere(collection, "Skull", (0.53 + (0.07 if heavy else 0), 0.44, 0.48), (0, 0, 2.42), bone)
    box(collection, "Jaw", (0.64, 0.32, 0.24), (0, -0.34, 2.12), dark, rotation=(math.radians(-8), 0, 0), bevel=0.045)
    for side in (-1, 1):
        box(collection, "SoulEye_%s" % side, (0.18, 0.10, 0.12), (side * 0.20, -0.43, 2.48), accent, rotation=(0, 0, math.radians(side * 8)), bevel=0.025)
        box(collection, "CheekBlade_%s" % side, (0.12, 0.32, 0.34), (side * 0.38, -0.22, 2.20), bone, rotation=(0, math.radians(side * 12), 0), bevel=0.025)
    box(collection, "CranialSpine", (0.16, 0.58, 0.18), (0, 0.12, 2.88), accent, rotation=(0, math.radians(-10), 0), bevel=0.025)

    # Open rib cage, luminous sternum and visible spine sell the revenant body.
    box(collection, "Sternum", (0.16, 0.22, 1.12), (0, -0.36, 1.40), accent, bevel=0.035)
    for rib in range(5):
        z = 1.82 - rib * 0.20
        width = plate * (0.96 - rib * 0.08)
        box(collection, "Rib_%02d" % rib, (width, 0.20, 0.11), (0, -0.29, z), bone, rotation=(0, 0, math.radians((-1 if rib % 2 else 1) * 2)), bevel=0.035)
    for vertebra in range(6):
        box(collection, "Spine_%02d" % vertebra, (0.26, 0.25, 0.13), (0, 0.32, 1.84 - vertebra * 0.22), dark, rotation=(0, 0, math.radians((vertebra % 2) * 5 - 2.5)), bevel=0.025)
    sphere(collection, "FrozenHeart", (0.24, 0.16, 0.29), (0, -0.42, 1.43), accent)
    box(collection, "Pelvis", (plate * 0.74, 0.38, 0.42), (0, -0.05, 0.62), bone, bevel=0.075)

    shoulder_size = 0.58 if heavy else (0.46 if medium else 0.34)
    for side in (-1, 1):
        label = "L" if side < 0 else "R"
        sphere(collection, "Scapula_%s" % label, (shoulder_size, 0.34, 0.28), (side * (0.82 if heavy else 0.70), 0, 1.68), bone)
        cylinder(collection, "ArmBone_%s" % label, 0.105 if heavy else 0.085, 1.08, (side * 0.88, 0, 1.03), bone, vertices=10)
        box(collection, "ForearmBlade_%s" % label, (0.30 if heavy else 0.23, 0.34, 0.72), (side * 0.90, -0.05, 0.62), dark, rotation=(0, math.radians(side * 6), 0), bevel=0.045)
        cylinder(collection, "Femur_%s" % label, 0.12 if heavy else 0.095, 0.92, (side * 0.38, 0, 0.02), bone, vertices=10)
        box(collection, "ShinBlade_%s" % label, (0.36 if heavy else 0.27, 0.36, 0.82), (side * 0.38, -0.08, -0.66), dark, bevel=0.055)
        box(collection, "Talon_%s" % label, (0.42, 0.76, 0.25), (side * 0.38, -0.19, -1.19), bone, bevel=0.055)

    for side in (-1, 1):
        cylinder(collection, "SoulJet_%s" % side, 0.16 if heavy else 0.12, 0.52, (side * 0.38, 0.53, 1.18), dark, rotation=(math.pi / 2, 0, 0), vertices=12)
        sphere(collection, "SoulFlame_%s" % side, (0.11, 0.20, 0.11), (side * 0.38, 0.72, 1.18), accent)


def build_ember_brood(collection, weight, accent):
    heavy = weight == "Heavy"
    medium = weight == "Medium"
    plate = 1.34 if heavy else (1.12 if medium else 0.92)
    shell = bpy.data.materials["MAT_EmberShell"]
    flesh = bpy.data.materials["MAT_EmberFlesh"]

    # Elongated crown, clustered eyes and mandibles form an alien profile.
    sphere(collection, "Cranium", (0.58 + (0.08 if heavy else 0), 0.56, 0.48), (0, 0.05, 2.42), shell)
    box(collection, "Crown", (0.34, 0.78, 0.28), (0, 0.22, 2.83), shell, rotation=(math.radians(14), 0, 0), bevel=0.06)
    for side in (-1, 1):
        sphere(collection, "HiveEye_%s" % side, (0.15, 0.08, 0.11), (side * 0.23, -0.51, 2.48), accent)
        box(collection, "Mandible_%s" % side, (0.14, 0.42, 0.18), (side * 0.27, -0.39, 2.19), flesh, rotation=(0, 0, math.radians(side * 22)), bevel=0.035)
        box(collection, "BrowSpike_%s" % side, (0.12, 0.44, 0.12), (side * 0.33, -0.17, 2.72), shell, rotation=(0, math.radians(side * 22), 0), bevel=0.02)

    # Overlapping carapace plates protect a visibly living molten core.
    for layer in range(4):
        z = 1.78 - layer * 0.27
        width = plate * (1.0 - layer * 0.09)
        box(collection, "ThoraxPlate_%02d" % layer, (width, 0.45, 0.30), (0, -0.20, z), shell, rotation=(math.radians(-6 - layer * 2), 0, 0), bevel=0.10)
    sphere(collection, "MoltenHeart", (0.27, 0.18, 0.34), (0, -0.50, 1.37), accent)
    for segment in range(4):
        sphere(collection, "Abdomen_%02d" % segment, (plate * (0.35 - segment * 0.025), 0.25, 0.17), (0, 0.04, 0.98 - segment * 0.19), flesh)
    box(collection, "DorsalCarapace", (plate * 0.90, 0.38, 1.08), (0, 0.40, 1.42), shell, rotation=(math.radians(5), 0, 0), bevel=0.10)

    shoulder_size = 0.62 if heavy else (0.49 if medium else 0.36)
    for side in (-1, 1):
        label = "L" if side < 0 else "R"
        sphere(collection, "CarapaceShoulder_%s" % label, (shoulder_size, 0.46, 0.34), (side * (0.84 if heavy else 0.71), 0, 1.68), shell)
        box(collection, "ShoulderSpike_%s" % label, (0.15, 0.18, 0.70 if heavy else 0.48), (side * (1.13 if heavy else 0.96), 0.05, 1.88), shell, rotation=(0, math.radians(side * 44), 0), bevel=0.02)
        sphere(collection, "UpperLimb_%s" % label, (0.21, 0.24, 0.56), (side * 0.88, 0, 1.02), flesh)
        box(collection, "ClawGuard_%s" % label, (0.32 if heavy else 0.25, 0.40, 0.72), (side * 0.90, -0.05, 0.61), shell, rotation=(0, math.radians(side * 7), 0), bevel=0.06)
        sphere(collection, "ThighMuscle_%s" % label, (0.26, 0.28, 0.48), (side * 0.39, 0, 0.02), flesh)
        box(collection, "ReverseShin_%s" % label, (0.38 if heavy else 0.29, 0.42, 0.82), (side * 0.39, -0.06, -0.65), shell, rotation=(math.radians(-4), 0, 0), bevel=0.07)
        box(collection, "ClawedFoot_%s" % label, (0.48, 0.82, 0.27), (side * 0.39, -0.24, -1.18), shell, bevel=0.07)

    for side in (-1, 1):
        cylinder(collection, "BioJet_%s" % side, 0.17 if heavy else 0.13, 0.50, (side * 0.40, 0.58, 1.17), flesh, rotation=(math.pi / 2, 0, 0), vertices=12)
        sphere(collection, "PlasmaVent_%s" % side, (0.12, 0.18, 0.12), (side * 0.40, 0.76, 1.17), accent)


def add_class_identity(collection, class_name, weight, accent, faction):
    heavy = weight == "Heavy"
    steel = bpy.data.materials["MAT_CryoIron"] if faction == "CryoRevenant" else bpy.data.materials["MAT_EmberShell"]

    if class_name == "Pathfinder":
        for side in (-1, 1):
            box(collection, "AeroFin_%s" % side, (0.12, 0.82, 0.76), (side * 0.66, 0.55, 1.52), accent, rotation=(0, math.radians(side * 22), 0), bevel=0.025)
    elif class_name == "Sentinel":
        cylinder(collection, "Rangefinder", 0.13, 0.48, (0.48, -0.34, 2.62), accent, rotation=(math.pi / 2, 0, 0), vertices=12)
    elif class_name == "Infiltrator":
        for index in range(5):
            box(collection, "CloakNode_%02d" % index, (0.14, 0.10, 0.14), ((index - 2) * 0.22, -0.61, 1.12), accent, bevel=0.025)
    elif class_name == "Technician":
        box(collection, "RepairSymbiote", (0.78, 0.55, 0.92), (0, 0.60, 1.28), steel, bevel=0.09)
        for side in (-1, 1):
            cylinder(collection, "ToolPod_%s" % side, 0.15, 0.76, (side * 0.52, 0.46, 1.10), steel, vertices=12)
    elif class_name == "Raider":
        for side in (-1, 1):
            cylinder(collection, "EMPCoil_%s" % side, 0.24, 0.16, (side * 0.53, -0.52, 1.32), accent, rotation=(math.pi / 2, 0, 0), vertices=16)
    elif class_name == "Juggernaut":
        sphere(collection, "SiegeReactor", (0.43, 0.25, 0.43), (0, 0.58, 1.56), accent)
    elif class_name == "Brute":
        box(collection, "RamPlate", (1.44, 0.28, 0.44), (0, -0.56, 1.78), accent, bevel=0.10)
        for side in (-1, 1):
            sphere(collection, "ShockNode_%s" % side, (0.22, 0.15, 0.22), (side * 0.54, -0.58, 1.25), accent)
    elif class_name == "Doombringer":
        for side in (-1, 1):
            cylinder(collection, "ShieldEmitter_%s" % side, 0.27, 0.18, (side * 0.62, -0.48, 1.52), accent, rotation=(math.pi / 2, 0, 0), vertices=16)


def build_armor(collection, class_name, weight, accent, faction):
    if faction == "CryoRevenant":
        build_cryo_revenant(collection, weight, accent)
    else:
        build_ember_brood(collection, weight, accent)
    add_class_identity(collection, class_name, weight, accent, faction)


def look_at(obj, target=(0, 0, 0.8)):
    obj.rotation_euler = (Vector(target) - obj.location).to_track_quat("-Z", "Y").to_euler()


def setup_render():
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_EEVEE"
    scene.render.resolution_x = 520
    scene.render.resolution_y = 650
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.view_settings.look = "AgX - Medium High Contrast"
    scene.world.color = (0.012, 0.018, 0.028)
    camera_data = bpy.data.cameras.new("ArmorCameraData")
    camera = bpy.data.objects.new("ArmorCamera", camera_data)
    scene.collection.objects.link(camera)
    scene.camera = camera
    camera.location = (5.4, -8.2, 4.3)
    camera.data.lens = 68
    look_at(camera)
    for name, location, energy, color in [
        ("Key", (4, -4, 7), 1100, (0.68, 0.82, 1.0)),
        ("Rim", (-4, 2, 5), 950, (1.0, 0.30, 0.10)),
        ("Fill", (2, 4, 3), 500, (0.24, 0.44, 1.0)),
    ]:
        data = bpy.data.lights.new(name + "Data", "AREA")
        data.energy = energy
        data.color = color
        data.size = 4
        light = bpy.data.objects.new(name, data)
        scene.collection.objects.link(light)
        light.location = location
        look_at(light)
    return camera


def meshes(collection):
    return [obj for obj in collection.objects if obj.type == "MESH"]


def triangles(collection):
    depsgraph = bpy.context.evaluated_depsgraph_get()
    total = 0
    for obj in meshes(collection):
        evaluated = obj.evaluated_get(depsgraph)
        mesh = evaluated.to_mesh()
        mesh.calc_loop_triangles()
        total += len(mesh.loop_triangles)
        evaluated.to_mesh_clear()
    return total


def export(collection, class_name):
    bpy.ops.object.select_all(action="DESELECT")
    parts = meshes(collection)
    for obj in parts:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.export_scene.fbx(
        filepath=os.path.join(EXPORT_DIR, class_name + "_Armor.fbx"),
        use_selection=True,
        object_types={"MESH"},
        apply_unit_scale=True,
        bake_space_transform=True,
        add_leaf_bones=False,
        mesh_smooth_type="FACE",
    )


clear_scene()
material("MAT_CryoBone", (0.34, 0.45, 0.52), 0.72, 0.20)
material("MAT_CryoIron", (0.012, 0.032, 0.050), 0.88, 0.22)
material("MAT_EmberShell", (0.055, 0.008, 0.012), 0.58, 0.25)
material("MAT_EmberFlesh", (0.26, 0.018, 0.012), 0.18, 0.34)
collections = []
definitions = []
for faction, team, color, faction_description in FACTIONS:
    accent = material("MAT_%s" % faction, color, 0.38, 0.18, 2.2)
    for class_name, weight, description in CLASSES:
        asset_name = "%s_%s" % (class_name, faction)
        if RENDER_FILTER is not None and RENDER_FILTER != asset_name:
            continue
        collection = bpy.data.collections.new(asset_name + "_Armor")
        bpy.context.scene.collection.children.link(collection)
        collections.append(collection)
        build_armor(collection, class_name, weight, accent, faction)
        definitions.append((asset_name, class_name, faction, team, weight, description, faction_description, collection))

camera = setup_render()
if RENDER_FILTER is None:
    bpy.ops.wm.save_as_mainfile(filepath=BLEND_PATH)
report = []
for asset_name, class_name, faction, team, weight, description, faction_description, collection in definitions:
    count = triangles(collection)
    if count <= 0 or count > 10000:
        raise RuntimeError("Triangle budget failed for %s: %d" % (asset_name, count))
    export(collection, asset_name)
    should_render = not SKIP_RENDER and (RENDER_FILTER is None or RENDER_FILTER == asset_name)
    if should_render:
        for candidate in collections:
            candidate.hide_render = candidate != collection
        bpy.context.scene.render.filepath = os.path.join(PREVIEW_DIR, asset_name + "_Armor.png")
        bpy.ops.render.render(write_still=True)
    report.append({
        "asset": asset_name,
        "class": class_name,
        "faction": faction,
        "team": team,
        "weight": weight,
        "description": "%s; %s" % (faction_description, description),
        "objects": len(meshes(collection)),
        "triangles": count,
        "fbx": "export/%s_Armor.fbx" % asset_name,
        "preview": "previews/%s_Armor.png" % asset_name if should_render else None,
    })

payload = {"blend": os.path.basename(BLEND_PATH), "faction_count": 2, "class_count": 9, "asset_count": len(report), "assets": report}
if RENDER_FILTER is None:
    with open(REPORT_PATH, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
print(json.dumps(payload, indent=2))
